// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOV-FgHMwQOuK-G5U_HiDaiD6yXB_cTgc',
    appId: '1:362855706630:web:68d100d6cbb5555d07d387',
    messagingSenderId: '362855706630',
    projectId: 'doctorcar-89952',
    authDomain: 'doctorcar-89952.firebaseapp.com',
    storageBucket: 'doctorcar-89952.appspot.com',
    measurementId: 'G-EEQ2SHMYNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgGDATB72t-qjRdluCymdOU6eMKgpqAw0',
    appId: '1:362855706630:android:faabe20f7ac273ac07d387',
    messagingSenderId: '362855706630',
    projectId: 'doctorcar-89952',
    storageBucket: 'doctorcar-89952.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy9nm2lGBpayz1HHDnP8r69Pg384DGlOA',
    appId: '1:362855706630:ios:e41e618416e9935007d387',
    messagingSenderId: '362855706630',
    projectId: 'doctorcar-89952',
    storageBucket: 'doctorcar-89952.appspot.com',
    androidClientId: '362855706630-2kr56ot4grpn9rs9a8kr80flf169vtdc.apps.googleusercontent.com',
    iosClientId: '362855706630-mqu1nbd8ngf9qm4k2ehl51bb37od3eh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy9nm2lGBpayz1HHDnP8r69Pg384DGlOA',
    appId: '1:362855706630:ios:b47d2a856936fd6d07d387',
    messagingSenderId: '362855706630',
    projectId: 'doctorcar-89952',
    storageBucket: 'doctorcar-89952.appspot.com',
    androidClientId: '362855706630-2kr56ot4grpn9rs9a8kr80flf169vtdc.apps.googleusercontent.com',
    iosClientId: '362855706630-nkalhmjiitdtbm64sdpc8hdpdsmh2r1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveDoctor.RunnerTests',
  );
}
