// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiStbc90yt6E3u6To1VSDDKoCp420QPhY',
    appId: '1:224155164215:web:6dded10498c4f2b1f729b2',
    messagingSenderId: '224155164215',
    projectId: 'drivedoctor-1a98c',
    authDomain: 'drivedoctor-1a98c.firebaseapp.com',
    storageBucket: 'drivedoctor-1a98c.appspot.com',
    measurementId: 'G-TNE1DZLQ41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfGl7iWwpkE6ybclssaA83Vzh0wNQc-_Q',
    appId: '1:224155164215:android:51c14da06047e488f729b2',
    messagingSenderId: '224155164215',
    projectId: 'drivedoctor-1a98c',
    storageBucket: 'drivedoctor-1a98c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-o97qNrbZH8e2pxbuJFtr3u8wTsT4QXI',
    appId: '1:224155164215:ios:222bd8821535e443f729b2',
    messagingSenderId: '224155164215',
    projectId: 'drivedoctor-1a98c',
    storageBucket: 'drivedoctor-1a98c.appspot.com',
    iosBundleId: 'com.example.driveDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-o97qNrbZH8e2pxbuJFtr3u8wTsT4QXI',
    appId: '1:224155164215:ios:fad6912ed8742ec7f729b2',
    messagingSenderId: '224155164215',
    projectId: 'drivedoctor-1a98c',
    storageBucket: 'drivedoctor-1a98c.appspot.com',
    iosBundleId: 'com.example.driveDoctor.RunnerTests',
  );
}
